---
settings:
  name: Cloud Volumes ONTAP 9.12.1 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-relnotes"
    version-number: 9.12.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9120-relnotes"
    version-number: 9.12.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9111-relnotes"
    version-number: 9.11.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9110-relnotes"
    version-number: 9.11.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9101-relnotes"
    version-number: 9.10.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9100-relnotes"
    version-number: 9.10.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-991-relnotes"
    version-number: 9.9.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-990-relnotes"
    version-number: 9.9.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-98-relnotes"
    version-number: '9.8'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-97-relnotes"
    version-number: '9.7'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-96-relnotes"
    version-number: '9.6'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-95-relnotes"
    version-number: '9.5'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-94-relnotes"
    version-number: '9.4'
  - name: Cloud de ONTAP
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Página principal de las notas de la versión
    url: "/index.html"
  - title: Novedades
    url: "/reference-new.html"
  - title: Información general sobre las licencias
    url: "/concept-licensing.html"
  - title: Configuraciones admitidas
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: Límites de almacenamiento
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: Problemas conocidos
    url: "/reference-issues.html"
  - title: Limitaciones conocidas
    entries:
    - title: Limitaciones comunes
      url: "/reference-limitations.html"
    - title: Limitaciones en AWS
      url: "/reference-limitations-aws.html"
    - title: Limitaciones en Azure
      url: "/reference-limitations-azure.html"
    - title: Limitaciones en Google Cloud
      url: "/reference-limitations-gcp.html"
  - title: Integraciones de proveedores de cloud
    url: "/reference-provider-integrations.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Novedades
      url: reference-new.html
    - title: Información general sobre las licencias
      url: concept-licensing.html
  - title: Amazon Web Services
    links:
    - title: Configuraciones admitidas
      url: reference-configs-aws.html
    - title: Límites de almacenamiento
      url: reference-limits-aws.html
    - title: Limitaciones
      url: reference-limitations-aws.html
  - title: Google Cloud
    links:
    - title: Configuraciones admitidas
      url: reference-configs-gcp.html
    - title: Límites de almacenamiento
      url: reference-limits-gcp.html
    - title: Limitaciones
      url: reference-limitations-gcp.html
  - title: Microsoft Azure
    links:
    - title: Configuraciones admitidas
      url: reference-configs-azure.html
    - title: Límites de almacenamiento
      url: reference-limits-azure.html
    - title: Limitaciones
      url: reference-limitations-azure.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://cloud.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toda la documentación de BlueXP
