---
settings:
  name: Cloud Volumes ONTAP release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 9.16.1
    url: "/cloud-volumes-ontap-relnotes"
  - version-number: 9.15.1
    url: "/cloud-volumes-ontap-9151-relnotes"
  - version-number: 9.15.0
    url: "/cloud-volumes-ontap-9150-relnotes"
  - version-number: 9.14.1
    url: "/cloud-volumes-ontap-9141-relnotes"
  - version-number: 9.14.0
    url: "/cloud-volumes-ontap-9140-relnotes"
  - version-number: 9.13.1
    url: "/cloud-volumes-ontap-9131-relnotes"
  - version-number: 9.13.0
    url: "/cloud-volumes-ontap-9130-relnotes"
  - version-number: 9.12.1
    url: "/cloud-volumes-ontap-9121-relnotes"
  - version-number: 9.12.0
    url: "/cloud-volumes-ontap-9120-relnotes"
  - version-number: 9.11.1
    url: "/cloud-volumes-ontap-9111-relnotes"
  - version-number: 9.11.0
    url: "/cloud-volumes-ontap-9110-relnotes"
  - version-number: 9.10.1
    url: "/cloud-volumes-ontap-9101-relnotes"
  - version-number: 9.10.0
    url: "/cloud-volumes-ontap-9100-relnotes"
  - version-number: 9.9.1
    url: "/cloud-volumes-ontap-991-relnotes"
  - version-number: 9.9.0
    url: "/cloud-volumes-ontap-990-relnotes"
  - version-number: '9.8'
    url: "/cloud-volumes-ontap-98-relnotes"
  - version-number: '9.7'
    url: "/cloud-volumes-ontap-97-relnotes"
  - version-number: '9.6'
    url: "/cloud-volumes-ontap-96-relnotes"
  - version-number: '9.5'
    url: "/cloud-volumes-ontap-95-relnotes"
  - version-number: '9.4'
    url: "/cloud-volumes-ontap-94-relnotes"
  - version-number: '9.3'
    url: "/cloud-volumes-ontap-93-relnotes"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Notas de la versión de Cloud Volumes ONTAP 9.16.1
    url: "/index.html"
  - title: Novedades
    url: "/reference-new.html"
  - title: Información general sobre las licencias
    url: "/concept-licensing.html"
  - title: Configuraciones admitidas
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: Límites de almacenamiento
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: Problemas conocidos
    url: "/reference-issues.html"
  - title: Limitaciones conocidas
    entries:
    - title: Limitaciones comunes
      url: "/reference-limitations.html"
    - title: Limitaciones en AWS
      url: "/reference-limitations-aws.html"
    - title: Limitaciones en Azure
      url: "/reference-limitations-azure.html"
    - title: Limitaciones en Google Cloud
      url: "/reference-limitations-gcp.html"
  - title: Integraciones de proveedores de cloud
    url: "/reference-provider-integrations.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
