---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en Azure para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos. 
---
= Límites de almacenamiento en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configure el sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP viene determinada por su licencia. La capacidad máxima del sistema incluye almacenamiento basado en disco y almacenamiento de objetos utilizado para la organización en niveles de datos.

NetApp no admite superar el límite de capacidad del sistema. Si alcanza el límite de capacidad con licencia, BlueXP muestra un mensaje de acción necesaria y ya no permite añadir discos adicionales.

[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GIB 


| PAYGO Explora | 2 TIB (la organización en niveles de los datos no es compatible con Explore) 


| Norma PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licencia basada en nodos | 2 PIB (requiere varias licencias) 


| Licencia basada en capacidad | 2 PIB 
|===
.Para alta disponibilidad, ¿el límite de capacidad de licencia por nodo o para todo el par de alta disponibilidad?
El límite de capacidad corresponde a todo el par de alta disponibilidad. No es por nodo. Por ejemplo, si utiliza la licencia Premium, puede tener hasta 368 TIB de capacidad entre ambos nodos.



== Límites del agregado

Cloud Volumes ONTAP usa almacenamiento de Azure como discos y los agrupa en _agregados_. Los agregados proporcionan almacenamiento para volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados | Igual que el límite de discos 


| Tamaño máximo de agregado hacia 1 | 384 TIB de capacidad bruta para un solo nodo, esto 2, 352 TIB de capacidad bruta para un único nodo con 96 TIB de capacidad bruta para pares de alta disponibilidad con blob de página, 384 TIB de capacidad bruta para pares de alta disponibilidad con discos gestionados 


| Discos por agregado | 1-12 hacia 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. El límite de capacidad del agregado se basa en los discos que componen el agregado. El límite no incluye el almacenamiento de objetos utilizado para la organización en niveles de datos.
. Si utiliza una licencia basada en nodo, se necesitan dos licencias BYOL para alcanzar los 384 TIB.
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de discos y almacenamiento por niveles por tamaño de equipo virtual

Los límites de capacidad son diferentes en función del tamaño de las máquinas virtuales que utilice y de si se utiliza un sistema de nodo único o un par de alta disponibilidad.

En las siguientes notas se ofrecen detalles sobre los números que verá en las siguientes tablas:

* Los límites de discos son específicos para los discos que contienen datos de usuario.
+
Los límites no incluyen el disco raíz, el disco principal y el VNVRAM.

* Una capacidad máxima del sistema se muestra cuando se utilizan solo discos y cuando se utilizan discos y organización en niveles de datos inactivos en el almacenamiento de objetos.
* Los sistemas de nodo único y alta disponibilidad que utilizan discos gestionados tienen un máximo de 32 TIB por disco. La cantidad de discos admitidos varía según el tamaño de la máquina virtual.
* Los sistemas DE ALTA DISPONIBILIDAD que usan los blobs de la página tienen un máximo de 8 TIB por blob de página. La cantidad de discos admitidos varía según el tamaño de la máquina virtual.
* El límite basado en disco de 896 TIB indicado para sistemas de un solo nodo con ciertos tamaños de máquina virtual es el límite _tested_.




=== Límites para licencias basadas en capacidad

Los siguientes límites de disco se aplican a los sistemas de Cloud Volumes ONTAP que utilizan un paquete de licencias basado en capacidad. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Obtenga información sobre las opciones de licencias de Cloud Volumes ONTAP"^]



==== Un solo nodo

[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| DS4_v2 | 29 | 896 TIB | 2 PIB 


| DS5_v2 | 61 | 896 TIB | 2 PIB 


| DS13_v2 | 29 | 896 TIB | 2 PIB 


| DS14_v2 | 61 | 896 TIB | 2 PIB 


| DS15_v2 | 61 | 896 TIB | 2 PIB 


| E4s_v3 | 5 | 160 TIB | 2 PIB 


| E8s_v3 | 13 | 416 TIB | 2 PIB 


| E32S_v3 | 29 | 896 TIB | 2 PIB 


| E48s_v3 | 29 | 896 TIB | 2 PIB 


| E64is_v3 | 29 | 896 TIB | 2 PIB 


| E4ds_v4 | 5 | 160 TIB | 2 PIB 


| E8ds_v4 | 13 | 416 TIB | 2 PIB 


| E32ds_v4 | 29 | 896 TIB | 2 PIB 


| E48ds_v4 | 29 | 896 TIB | 2 PIB 


| E80ids_v4 | 61 | 896 TIB | 2 PIB 


| L8S_v3 | 12 | 384 TIB | 2 PIB 


| L16s_v3 | 28 | 896 TIB | 2 PIB 


| L32s_v3 | 28 | 896 TIB | 2 PIB 


| L48s_v3 | 28 | 896 TIB | 2 PIB 


| L64s_v3 | 28 | 896 TIB | 2 PIB 
|===


==== Pares de ALTA DISPONIBILIDAD en una única zona de disponibilidad con Blobs de página

[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| DS4_v2 | 29 | 232 TIB | 2 PIB 


| DS5_v2 | 61 | 488 TIB | 2 PIB 


| DS13_v2 | 29 | 232 TIB | 2 PIB 


| DS14_v2 | 61 | 488 TIB | 2 PIB 


| DS15_v2 | 61 | 488 TIB | 2 PIB 


| E8s_v3 | 13 | 104 TIB | 2 PIB 


| E48s_v3 | 29 | 232 TIB | 2 PIB 


| E8ds_v4 | 13 | 104 TIB | 2 PIB 


| E32ds_v4 | 29 | 232 TIB | 2 PIB 


| E48ds_v4 | 29 | 232 TIB | 2 PIB 


| E80ids_v4 | 61 | 488 TIB | 2 PIB 
|===


==== Pares DE ALTA DISPONIBILIDAD en una única zona de disponibilidad con discos gestionados compartidos

[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| E8ds_v4 | 12 | 384 TIB | 2 PIB 


| E32ds_v4 | 28 | 896 TIB | 2 PIB 


| E48ds_v4 | 28 | 896 TIB | 2 PIB 


| E80ids_v4 | 28 | 896 TIB | 2 PIB 


| L16s_v3 | 28 | 896 TIB | 2 PIB 


| L32s_v3 | 28 | 896 TIB | 2 PIB 


| L48s_v3 | 28 | 896 TIB | 2 PIB 


| L64s_v3 | 28 | 896 TIB | 2 PIB 
|===


==== Pares DE ALTA DISPONIBILIDAD en múltiples zonas de disponibilidad con discos gestionados compartidos

[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| E8ds_v4 | 12 | 384 TIB | 2 PIB 


| E32ds_v4 | 28 | 896 TIB | 2 PIB 


| E48ds_v4 | 28 | 896 TIB | 2 PIB 


| E80ids_v4 | 28 | 896 TIB | 2 PIB 


| L48s_v3 | 28 | 896 TIB | 2 PIB 


| L64s_v3 | 28 | 896 TIB | 2 PIB 
|===


=== Límites para licencias basadas en nodos

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que utilizan licencias basadas en nodos, que es el modelo de licencias de la generación anterior que le permitió obtener licencias de Cloud Volumes ONTAP por nodo. La licencia basada en nodos sigue estando disponible para los clientes existentes.

Puede comprar varias licencias basadas en nodos para un sistema de nodo único BYOL de Cloud Volumes ONTAP o de parejas de alta disponibilidad para asignar más de 368 TiB de capacidad, hasta el límite máximo de capacidad del sistema probado y compatible de 2 PIB. Tenga en cuenta que los límites de disco pueden impedir que llegue al límite de capacidad utilizando solo discos. Puede superar el límite de discos mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Aprenda a añadir licencias de sistema adicionales a Cloud Volumes ONTAP"^]. Aunque Cloud Volumes ONTAP admite hasta la capacidad del sistema máxima probada y admitida de 2 PIB, si se supera el límite de 2 PIB, la configuración del sistema no es compatible.



==== Un solo nodo

Un único nodo tiene dos opciones de licencia basadas en nodos: PAYGO Premium y BYOL.

.Un solo nodo con PAYGO Premium
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data por nodo | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| DS5_v2 | 61 | 368 TIB | 368 TIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB 


| E32S_v3 | 29 | 368 TIB | 368 TIB 


| E48s_v3 | 29 | 368 TIB | 368 TIB 


| E64is_v3 | 29 | 368 TIB | 368 TIB 


| E32ds_v4 | 29 | 368 TIB | 368 TIB 


| E48ds_v4 | 29 | 368 TIB | 368 TIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB 
|===
====
.Un nodo único con BYOL
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de la máquina virtual | Discos MAX Data por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + organización en niveles de datos* | *Solo discos* | *Discos + organización en niveles de datos* 


| DS4_v2 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS5_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS13_v2 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| L8S_v2 | 13 | 368 TIB | 368 TIB | 416 TIB | 2 PIB 


| E4s_v3 | 5 | 160 TIB | 368 TIB | 160 TIB | 2 PIB 


| E8s_v3 | 13 | 368 TIB | 368 TIB | 416 TIB | 2 PIB 


| E32S_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E48s_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E64is_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E4ds_v4 | 5 | 160 TIB | 368 TIB | 160 TIB | 2 PIB 


| E8ds_v4 | 13 | 368 TIB | 368 TIB | 416 TIB | 2 PIB 


| E32ds_v4 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E48ds_v4 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 
|===
====


==== Parejas de HA

Las parejas de ALTA DISPONIBILIDAD tienen dos tipos de configuración: BLOB de página y varias zonas de disponibilidad. Cada configuración tiene dos opciones de licencia basadas en nodos: PAYGO Premium y BYOL.

.PAYGO Premium: Pares DE HA en una sola zona de disponibilidad con Blobs de página
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| DS5_v2 | 61 | 368 TIB | 368 TIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB 


| E8s_v3 | 13 | 104 TIB | 368 TIB 


| E48s_v3 | 29 | 232 TIB | 368 TIB 


| E32ds_v4 | 29 | 232 TIB | 368 TIB 


| E48ds_v4 | 29 | 232 TIB | 368 TIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB 
|===
====
.PAYGO Premium: Pares DE ALTA DISPONIBILIDAD en una configuración de múltiples zonas de disponibilidad con discos gestionados compartidos
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad | Máx. De capacidad del sistema solo con discos | Max capacidad del sistema con discos y organización en niveles de los datos 


| E32ds_v4 | 28 | 368 TIB | 368 TIB 


| E48ds_v4 | 28 | 368 TIB | 368 TIB 


| E80ids_v4 | 28 | 368 TIB | 368 TIB 
|===
====
.BYOL: Pares de ALTA DISPONIBILIDAD en una sola zona de disponibilidad con Blobs de página
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + organización en niveles de datos* | *Solo discos* | *Discos + organización en niveles de datos* 


| DS4_v2 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| DS5_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| DS13_v2 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| E8s_v3 | 13 | 104 TIB | 368 TIB | 104 TIB | 2 PIB 


| E48s_v3 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| E8ds_v4 | 13 | 104 TIB | 368 TIB | 104 TIB | 2 PIB 


| E32ds_v4 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| E48ds_v4 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 
|===
====
.BYOL: Pares de ALTA DISPONIBILIDAD en una configuración de zona de disponibilidad múltiples con discos gestionados compartidos
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de la máquina virtual | Discos MAX Data para una pareja de alta disponibilidad 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + organización en niveles de datos* | *Solo discos* | *Discos + organización en niveles de datos* 


| E8ds_v4 | 12 | 368 TIB | 368 TIB | 368 TIB | 2 PIB 


| E32ds_v4 | 28 | 368 TIB | 368 TIB | 368 TIB | 2 PIB 


| E48ds_v4 | 28 | 368 TIB | 368 TIB | 368 TIB | 2 PIB 


| E80ids_v4 | 28 | 368 TIB | 368 TIB | 368 TIB | 2 PIB 
|===
====


== Límites de máquinas virtuales de almacenamiento

Algunas configuraciones le permiten crear máquinas virtuales de almacenamiento (SVM) adicionales para Cloud Volumes ONTAP.

Estos son los límites probados. Aunque teóricamente es posible configurar más equipos virtuales de almacenamiento, no lo es.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Aprenda a crear máquinas virtuales de almacenamiento adicionales"^].

[cols="2*"]
|===
| Tipo de licencia | Límite de VM de almacenamiento 


| *Freemium*  a| 
24 equipos virtuales de almacenamiento total hacia 1,2



| *PAYGO basado en la capacidad o BYOL* esta 3  a| 
24 equipos virtuales de almacenamiento total hacia 1,2



| *BYOL* basado en nodos con esta versión 4  a| 
24 equipos virtuales de almacenamiento total hacia 1,2



| *PAYGO* basado en nodos  a| 
* 1 equipo virtual de almacenamiento para proporcionar datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres


|===
. Estos 24 equipos virtuales de almacenamiento pueden proporcionar datos o configurarse para recuperación ante desastres (DR).
. Cada equipo virtual de almacenamiento puede tener hasta tres LIF, donde dos son LIF de datos y uno es LIF de gestión de SVM.
. Para las licencias basadas en la capacidad, no hay costes de licencias adicionales para equipos virtuales de almacenamiento adicionales, pero hay un cargo mínimo de capacidad de 4 TIB por equipo virtual de almacenamiento. Por ejemplo, si crea dos VM de almacenamiento y cada una tiene 2 TIB de capacidad aprovisionada, se le cobrará un total de 8 TIB.
. Para BYOL basado en nodos, se requiere una licencia complementaria para cada equipo virtual de almacenamiento que _data-sirviendo_ adicional más allá de la primera máquina virtual de almacenamiento que se suministra con Cloud Volumes ONTAP de forma predeterminada. Póngase en contacto con el equipo de cuenta para obtener una licencia adicional de máquina virtual de almacenamiento.
+
Los equipos virtuales de almacenamiento que configure para la recuperación ante desastres (DR) no requieren una licencia adicional (son gratuitos), sino que cuentan con el límite de equipos virtuales de almacenamiento. Por ejemplo, si tiene 12 máquinas virtuales de almacenamiento que sirven datos y 12 máquinas virtuales de almacenamiento configuradas para recuperación ante desastres, ha alcanzado el límite y no puede crear ningún equipo virtual de almacenamiento adicional.





== Límites de archivos y volúmenes

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo | 16 TIB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2000 millones 


| *Volúmenes FlexClone* | Profundidad de clonación jerárquica hacia 1 | 499 


.3+| *Volúmenes FlexVol* | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo | 100 TIB 


| *Qtrees* | Máximo por volumen FlexVol | 4,995 


| *Copias Snapshot* | Máximo por volumen FlexVol | 1,023 
|===
. La profundidad de clon jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un único volumen de FlexVol.




== Límites de almacenamiento de iSCSI

[cols="3*"]
|===
| Almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1,024 


| Número máximo de mapas de LUN | 1,024 


| Tamaño máximo | 16 TIB 


| Máximo por volumen | 512 


| *grupos* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1,024 


.2+| *LIF* | Máximo por puerto | 32 


| Máximo por conjunto de puertos | 32 


| *Portsets* | Máximo por nodo | 256 
|===