---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.16.1 incluye una nueva mejora. 
---
= Novedades en Cloud Volumes ONTAP 9.16.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.16.1 incluye nuevas mejoras.

Las últimas versiones de BlueXP también incluyen funciones y mejoras adicionales. Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de la versión de BlueXP"^] para obtener más detalles.



== 9.16.1 P3 (29 de mayo de 2025)

La revisión 9.16.1 P3 ahora puede ponerse en marcha y actualizarse para Cloud Volumes ONTAP en Azure y Google Cloud. Sin embargo, esta versión no está disponible para implementar y actualizar en AWS. BlueXP le solicitará que actualice sus sistemas existentes a esta versión de revisión.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["Consulte la lista de errores solucionados en la revisión P3"^] (Se requiere inicio de sesión en el sitio de soporte de NetApp).



== 9.16.1 P2 (17 de abril de 2025)

La revisión 9.16.1 P2 ahora puede ponerse en marcha y actualizarse para Cloud Volumes ONTAP en Azure y Google Cloud. Sin embargo, esta versión no está disponible para implementar y actualizar en AWS. BlueXP le solicitará que actualice sus sistemas existentes a esta versión de revisión.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["Consulte la lista de errores solucionados en la revisión P2"^] (Se requiere inicio de sesión en el sitio de soporte de NetApp).



== 9.16.1 P1 (17 de abril de 2025)

La revisión 9.16.1 P1 ahora puede ponerse en marcha y actualizarse para Cloud Volumes ONTAP en Azure y Google Cloud. Sin embargo, esta versión no está disponible para implementar y actualizar en AWS. BlueXP le solicitará que actualice sus sistemas existentes a esta versión de revisión.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["Consulte la lista de errores solucionados en la revisión P1"^] (Se requiere inicio de sesión en el sitio de soporte de NetApp).



== 9.16.1 GA (6 de marzo de 2025)

Ahora puede utilizar la versión de disponibilidad general de Cloud Volumes ONTAP 9.16.1 para implementar y actualizar en Azure y Google Cloud. Sin embargo, esta versión no está disponible para implementar y actualizar en AWS.



== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].



=== Ruta de actualización admitida

Puede actualizar a Cloud Volumes ONTAP 9.16.1 GA desde la versión 9.15.1 en Azure y Google Cloud. BlueXP le solicitará que actualice los sistemas Cloud Volumes ONTAP aptos a esta versión.


NOTE: Para AWS, no se le pedirá esta actualización. AWS no admite la actualización a Cloud Volumes ONTAP 9.16.1 GA.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad es sin interrupciones y las I/O no interrumpen. Durante este proceso de actualización no disruptivo, cada nodo se actualiza en tándem para continuar sirviendo I/O a los clientes.

