---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.15.1 incluye una nueva mejora. 
---
= Novedades en Cloud Volumes ONTAP 9.15.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.15.1 incluye nuevas mejoras.

Las últimas versiones de BlueXP también incluyen funciones y mejoras adicionales. Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de la versión de BlueXP"^] para obtener más detalles.



== 9.15.1 P1 (3 de septiembre de 2024)

El parche 9.15.1 P1 ya está disponible para Cloud Volumes ONTAP para todos los proveedores de cloud. BlueXP le solicitará que actualice sus sistemas existentes a esta versión de revisión.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.15.1P1["Consulte la lista de errores solucionados en la revisión P1"^] (Se requiere inicio de sesión en el sitio de soporte de NetApp).



== 9.15.1 GA (22 agosto 2024)

La GA de Cloud Volumes ONTAP 9.15.1 ya está disponible en AWS, Azure y Google Cloud. La versión GA está disponible para su despliegue y actualización.

Esta versión incluye las siguientes funciones y mejoras para Azure. Siga leyendo para obtener más información sobre las configuraciones específicas que admiten estas nuevas funciones.



=== Compatibilidad con discos gestionados Premium SSD v2 en Azure

Los discos gestionados de SSD Premium v2 ahora son compatibles con los sistemas Cloud Volumes ONTAP en Azure. Estos discos premium proporcionan un mayor rendimiento con una menor latencia a un coste menor tanto para pares de nodos únicos como de alta disponibilidad (HA), en comparación con los discos gestionados SSD Premium. Al igual que otros discos gestionados, el tamaño máximo del disco es de 32 TiB. Se puede configurar el rendimiento (capacidad, rendimiento e IOPS) de los discos gestionados v2 SSD Premium, lo que permite que las cargas de trabajo sean rentables y satisfagan las cambiantes necesidades de rendimiento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage.html#azure-storage["Obtenga más información sobre el almacenamiento de Azure"^].



=== Ponga en marcha pares de alta disponibilidad en zonas de disponibilidad individuales de Azure

A partir de Cloud Volumes ONTAP 9.15.1, puede poner en marcha instancias de máquinas virtuales (VM) en modo HA en zonas de disponibilidad única (AZs) en Azure. A diferencia de las puestas en marcha no pertenecientes a zonas anteriores, Cloud Volumes ONTAP 9.15.1 utiliza conjuntos de escala de máquinas virtuales de Microsoft en modo de orquestación flexible para poner en marcha todos los recursos, incluidos dominios de fallo independientes dentro del mismo área de disponibilidad, lo que garantiza una disponibilidad óptima. Este modo de implementación, de forma predeterminada, utiliza discos gestionados Premium SSD v2 cuando se cumplen los siguientes criterios:

* La versión de Cloud Volumes ONTAP es 9.15.1 o posterior.
* La región y zona seleccionadas admiten discos gestionados Premium SSD v2. Para obtener información sobre las regiones admitidas, consulte  https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Sitio web de Microsoft Azure: Productos disponibles por región"^]. Para saber cómo agregarlos, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html#launching-a-cloud-volumes-ontap-ha-pair-in-azure["Iniciar una pareja de alta disponibilidad de Cloud Volumes ONTAP en Azure"^] .
* La suscripción está registrada para `Microsoft.Compute/VMOrchestratorZonalMultiFD` la función de Microsoft. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-saz-feature.html["Aprenda a habilitar VMOrchestratorZonalMultiFD para zonas de disponibilidad únicas"^].


Si alguno de estos criterios no se cumple, se aplica el modo de implementación no zonal anterior para el almacenamiento redundante local (LRS).



=== Compatibilidad con Virtual Machines Scale Sets para unificar todos los tipos de alta disponibilidad de Azure

Cloud Volumes ONTAP 9.15.1 aprovecha los conjuntos de escala de máquinas virtuales en el modo de orquestación flexible de Azure para implementar instancias de máquinas virtuales (VM) en zonas de disponibilidad únicas para pares de alta disponibilidad (HA). Cubre todos los tipos del modo HA, Pageblob, LRS, almacenamiento redundante de zona (ZRS) o multizona, y zona LRS (AZ única).

* https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/["Documentación de Microsoft Azure: Documentación de Virtual Machine Scale Sets"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["Obtenga información sobre pares de alta disponibilidad en Azure"^].




== Notas de actualización.

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].



=== Ruta de actualización admitida

Puede actualizar a Cloud Volumes ONTAP 9.15.1 desde versiones 9.15.0 y 9.14.1. BlueXP le solicitará que actualice los sistemas Cloud Volumes ONTAP aptos a esta versión.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad no provoca interrupciones y la I/o se realiza de forma ininterrumpida. Durante este proceso de actualización no disruptiva, cada nodo se actualiza conjuntamente para seguir proporcionando I/o a los clientes.




=== las instancias c4, m4 y r4 ya no son compatibles

En AWS, los tipos de instancias c4, m4 y r4 EC2 ya no son compatibles con Cloud Volumes ONTAP. Si tiene un sistema existente que se ejecuta en un tipo de instancia c4, m4 o r4, debe cambiar a un tipo de instancia en la familia de instancias c5, m5 o r5. No puede actualizar a esta versión hasta que cambie el tipo de instancia.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda a cambiar el tipo de instancia de EC2 para Cloud Volumes ONTAP"^].

Consulte link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Soporte de NetApp"^] para obtener más información acerca del fin de la disponibilidad y la compatibilidad con estos tipos de instancia.
