---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas de Cloud Volumes ONTAP en todos los proveedores de cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Las siguientes limitaciones se aplican a Cloud Volumes ONTAP en todos los proveedores de cloud: AWS, Azure y Google Cloud.



== Funciones ONTAP no compatibles

Cloud Volumes ONTAP no admite las siguientes funciones:

* Deduplicación inline a nivel de agregado
* Deduplicación en segundo plano a nivel de agregado
* Centro de mantenimiento de discos
* El saneamiento de disco
* Mirroring de FabricPool
* Fibre Channel (FC)
* Flash Pool
* Infinite Volume
* Grupos de interfaces
* Conmutación al nodo de respaldo LIF de Itranode
* MetroCluster
* Verificación de varios administradores
+
Si se habilita la verificación multi-administrador en Cloud Volumes ONTAP, se genera una configuración no compatible.

* RAID4, RAID-DP, RAID-TEC (compatible con RAID0)
* Procesador de servicios
* Modos empresariales y cumplimiento de normativas para SnapLock (solo es compatible WORM de cloud)
* SnapMirror síncrono
* VLAN
* Disponibilidad continua (CA) para PYMES
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Acciones SMB disponibles continuamente"^] No se admiten operaciones no disruptivas.





== Máximo de operaciones de replicación simultáneas

El número máximo de transferencias simultáneas de SnapMirror o SnapVault para Cloud Volumes ONTAP es 100 por nodo, independientemente del tipo de instancia o de tipo de máquina.



== No se deben usar copias Snapshot de proveedores de cloud para sus planes de backup y recuperación

No debería usar las copias Snapshot de su proveedor de cloud como parte de su plan de backup y recuperación de datos de Cloud Volumes ONTAP. Debería usar siempre copias Snapshot de ONTAP o soluciones de backup de terceros para realizar backups y restaurar datos alojados en Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Aprenda a utilizar NetApp Backup and Recovery para realizar copias de seguridad y restaurar datos de ONTAP"^] .


NOTE: Los puntos de consistencia de ONTAP del sistema de archivos WAFL determinan la coherencia de datos. Solo ONTAP puede desactivar el sistema de archivos WAFL para realizar un backup consistente con los fallos.



== Cloud Volumes ONTAP solo admite instancias de máquinas virtuales reservadas y bajo demanda

Cloud Volumes ONTAP puede ejecutarse en una instancia de máquina virtual reservada o bajo demanda desde el proveedor de cloud. No se admiten otros tipos de instancias de VM.



== No deben utilizarse soluciones automáticas de gestión de recursos de aplicaciones

Las soluciones de administración automática de recursos de aplicaciones no deben gestionar los sistemas Cloud Volumes ONTAP. Si lo hace, puede provocar un cambio en una configuración no compatible. Por ejemplo, la solución puede cambiar Cloud Volumes ONTAP por un tipo de instancia de máquina virtual no compatible.



== Las actualizaciones de software deben ser completadas por la consola de NetApp

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde la consola de NetApp . No debe actualizar Cloud Volumes ONTAP mediante el Administrador del sistema o la CLI. Hacerlo puede afectar la estabilidad del sistema.



== La implementación de Cloud Volumes ONTAP no se debe modificar desde la consola de su proveedor de cloud

Los cambios en la configuración de Cloud Volumes ONTAP desde la consola de su proveedor de nube dan como resultado una configuración no compatible. Cualquier cambio en los recursos de Cloud Volumes ONTAP que la consola crea y administra puede afectar la estabilidad del sistema y la capacidad de la consola para administrar el sistema.


NOTE: Después de la implementación inicial, se admite la modificación del nombre de la suscripción de Azure utilizado para los recursos de Cloud Volumes ONTAP.



== Los discos y agregados deben administrarse desde la consola

Todos los discos y agregados deben crearse y eliminarse directamente desde la consola. No debe realizar estas acciones desde otra herramienta de administración. Hacerlo puede afectar la estabilidad del sistema, obstaculizar la capacidad de agregar discos en el futuro y potencialmente generar tarifas redundantes del proveedor de la nube.



== Limitación de la licencia de SnapManager

Las licencias de SnapManager por servidor son compatibles con Cloud Volumes ONTAP. No se admiten licencias por sistema de almacenamiento (suite SnapManager).



== Limitaciones con agentes y extensiones de terceros

Los agentes de terceros y las extensiones de VM no son compatibles con las instancias de máquina virtual de Cloud Volumes ONTAP.
