---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1 incluye una nueva mejora. 
---
= Novedades de Cloud Volumes ONTAP 9.12.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1 incluye nuevas mejoras.

También se incluyen funciones y mejoras adicionales en las versiones más recientes de BlueXP (anteriormente Cloud Manager). Consulte https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notas de la versión de BlueXP"^] para obtener más detalles.



== 9.12.1 GA (9 de febrero de 2023)

La versión de disponibilidad general (GA) de Cloud Volumes ONTAP 9.12.1 ya está disponible en AWS, Azure y Google Cloud. La versión de GA incluye correcciones de errores.



== 9.12.1 RC1 (8 de diciembre de 2022)

La primera versión candidata al lanzamiento de Cloud Volumes ONTAP 9.12.1 ya está disponible en AWS, Azure y Google Cloud. Esta versión incluye las siguientes funciones y mejoras nuevas.



=== Licencia de ONTAP S3 en GCP

Ahora se incluye una licencia de ONTAP S3 en los sistemas Cloud Volumes ONTAP nuevos y existentes que ejecutan la versión 9.12.1 o posterior en Google Cloud Platform.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Aprenda a configurar y gestionar los servicios de almacenamiento de objetos S3 en ONTAP"^]



=== Compatibilidad con NVMe-TCP en Cloud Volumes ONTAP

NVMe-TCP es compatible con los proveedores de cloud si utiliza Cloud Volumes ONTAP versión 9.12.1 o posterior. BlueXP no ofrece funcionalidades de gestión para NVMe-TCP.

Para obtener más información sobre cómo configurar NVMe mediante ONTAP, consulte link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Configure una máquina virtual de almacenamiento para NVMe"^].



=== Alta disponibilidad de Azure en una zona de disponibilidad única con discos gestionados compartidos

Ahora puede implementar una configuración de alta disponibilidad de Cloud Volumes ONTAP usando el almacenamiento redundante local (LRS) de Microsoft Azure que se ejecuta sobre discos gestionados compartidos. El sistema de almacenamiento redundante local replica sus datos tres veces en un solo centro de datos de la misma región.

Para obtener más información sobre los componentes y la arquitectura de configuración de alta disponibilidad, consulte link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Pares de alta disponibilidad en Azure"^].

Cuando implemente un nuevo par de alta disponibilidad en Azure en una única zona de disponibilidad, ahora utilizará discos gestionados compartidos LRS en lugar de Blobs de página para el almacenamiento. No hay ningún cambio en el asistente de entorno de trabajo. Solo tiene que elegir una única zona de disponibilidad para utilizar esta nueva configuración. Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Iniciar una pareja de alta disponibilidad de Cloud Volumes ONTAP en Azure"^].



=== Alta disponibilidad de Azure en varias zonas de disponibilidad con discos gestionados compartidos

Ahora puede implementar una configuración de alta disponibilidad de Cloud Volumes ONTAP utilizando varias zonas de disponibilidad de Azure en una región. La nueva configuración protege contra el fallo del centro de datos y mantiene la disponibilidad de las aplicaciones con el uso de discos gestionados compartidos de almacenamiento redundante de zonas (ZRS) de Azure. Esta función está disponible actualmente sólo en las regiones de Europa Occidental 2, Europa Occidental, Europa del Norte y Francia Central.

Para obtener más información sobre los componentes y la arquitectura de configuración de alta disponibilidad, consulte link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Pares de alta disponibilidad en Azure"^].

Para utilizar esta nueva configuración, consulte link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Iniciar una pareja de alta disponibilidad de Cloud Volumes ONTAP en Azure"^].

Para obtener más información acerca del almacenamiento redundante de zonas para discos administrados, consulte link:https://learn.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks["Documentación de Microsoft Azure."]



== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].



=== Ruta de actualización admitida

Puede actualizar a Cloud Volumes ONTAP 9.12.1 desde las versiones 9.12.0 y 9.11.1. BlueXP le solicitará que actualice los sistemas Cloud Volumes ONTAP aptos a esta versión.



=== Versión necesaria del conector

El conector BlueXP debe estar ejecutando la versión 3.9.24 o posterior para implementar nuevos sistemas Cloud Volumes ONTAP 9.12.1 y actualizar los sistemas existentes a la versión 9.12.1.


TIP: Las actualizaciones automáticas del conector están habilitadas de forma predeterminada, por lo que debería estar ejecutando la última versión.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad no provoca interrupciones y la I/o se realiza de forma ininterrumpida. Durante este proceso de actualización no disruptiva, cada nodo se actualiza conjuntamente para seguir proporcionando I/o a los clientes.




=== las instancias c4, m4 y r4 ya no son compatibles

En AWS, los tipos de instancias c4, m4 y r4 EC2 ya no son compatibles con Cloud Volumes ONTAP. Si tiene un sistema existente que se ejecuta en un tipo de instancia c4, m4 o r4, debe cambiar a un tipo de instancia en la familia de instancias c5, m5 o r5.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda a cambiar el tipo de instancia de EC2 para Cloud Volumes ONTAP"^].

Consulte link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Soporte de NetApp"^] para obtener más información acerca del fin de la disponibilidad y la compatibilidad con estos tipos de instancia.
