---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 incluye una nueva mejora. 
---
= Novedades de Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 está disponible para implementación y actualización en Azure y Google Cloud.



== 9.17.1 RC1 (4 de septiembre de 2025)

Ahora puede usar la versión candidata 1 de Cloud Volumes ONTAP 9.17.1 para la implementación y actualización en Azure y Google Cloud. Sin embargo, esta versión no está disponible para su implementación y actualización en AWS.



== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].



=== Ruta de actualización admitida

Puede actualizar a Cloud Volumes ONTAP 9.17.1 RC1 desde la versión 9.16.1 en Azure y Google Cloud.  BlueXP le solicitará que actualice los sistemas Cloud Volumes ONTAP elegibles a esta versión.


NOTE: En el caso de AWS, no se le solicitará esta actualización.  La actualización a Cloud Volumes ONTAP 9.17.1 RC1 no es compatible con AWS.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad es sin interrupciones y las I/O no interrumpen. Durante este proceso de actualización no disruptivo, cada nodo se actualiza en tándem para continuar sirviendo I/O a los clientes.

