---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Estas limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. 
---
= Limitaciones conocidas de Cloud Volumes ONTAP en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. No olvide revisar también link:reference-limitations.html["Limitaciones para Cloud Volumes ONTAP en todos los proveedores de cloud"].



== Limitaciones del uso de extensiones de Azure VM

Cloud Volumes ONTAP no admite extensiones de máquinas virtuales (VM) de Azure porque afectan las operaciones de administración de BlueXP .  Durante la implementación, BlueXP evita la instalación de cualquier extensión en sus máquinas virtuales.  Si ya hay extensiones instaladas en sus máquinas virtuales de Cloud Volumes ONTAP existentes, comuníquese con el soporte técnico de Microsoft Azure para eliminarlas.  Para obtener orientación, consulte el artículo de la base de conocimientos (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["¿Se pueden instalar Azure VM Management Extensions en Cloud Volume ONTAP?"^]

A partir del 14 de julio de 2025, NetApp enviará correos electrónicos y le notificará en BlueXP si se detectan extensiones de VM en sus VM de Cloud Volumes ONTAP .



== Limitaciones de Flash Cache

Cloud Volumes ONTAP utiliza el almacenamiento NVMe local en algunos tipos de máquinas virtuales como _Flash Cache_. Tenga en cuenta esta limitación:

* No se admite el recalentamiento de la caché tras un reinicio.




== Limitaciones de las puestas en marcha de alta disponibilidad

Los pares de alta disponibilidad (HA) no se admiten en algunas regiones.

https://bluexp.netapp.com/cloud-volumes-global-regions["Consulte la lista de regiones de Azure admitidas"^].



== Limitaciones de las puestas en marcha de alta disponibilidad en zonas de disponibilidad únicas

A partir de Cloud Volumes ONTAP 9.15.1, puede poner en marcha instancias de máquinas virtuales (VM) en modo HA en zonas de disponibilidad única (AZs) en Azure. Para obtener más información sobre los criterios que admiten esta función, consulte https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Ponga en marcha pares de alta disponibilidad en zonas de disponibilidad individuales de Azure"^] .

Si la versión de Cloud Volumes ONTAP es anterior a la 9.15.1 o si no se cumple alguna de estas condiciones, se aplica el modelo de puesta en marcha anterior que utiliza conjuntos de disponibilidad. Esto sólo se aplica a configuraciones de alta disponibilidad.
