---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.18.1 incluye una nueva mejora. 
---
= Novedades en Cloud Volumes ONTAP 9.18.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ya puedes desplegar y actualizar a Cloud Volumes ONTAP 9.18.1. Puedes ver la versión base de este lanzamiento y las últimas versiones de parches disponibles para desplegar y actualizar en la NetApp Console.

Para conocer las funciones de Cloud Volumes ONTAP que se han introducido en las últimas versiones de la NetApp Console, mira qué hay de nuevo en https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^].



== 9.18.1 GA (10 de febrero de 2026)

La versión Cloud Volumes ONTAP 9.18.1 General Availability ya está disponible para despliegue y actualización en Amazon Web Services (AWS) y Microsoft Azure. Esta versión no está disponible para despliegue y actualización en Google Cloud.



== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde la consola. No debe actualizar Cloud Volumes ONTAP mediante el Administrador del sistema o la CLI. Hacerlo puede afectar la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprende cómo actualizar cuando la consola te lo notifique"^] .



=== Ruta de actualización admitida

Puedes actualizar a Cloud Volumes ONTAP 9.18.1 desde la 9.17.1 P1 y parches posteriores en AWS y Azure. La NetApp Console te pedirá que actualices los sistemas Cloud Volumes ONTAP elegibles a esta versión.


NOTE: Cloud Volumes ONTAP 9.18.1 no está disponible para upgrade en Google Cloud.



=== Tiempo de inactividad

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad es sin interrupciones y las I/O no interrumpen. Durante este proceso de actualización no disruptivo, cada nodo se actualiza en tándem para continuar sirviendo I/O a los clientes.

