---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud admite varias configuraciones de Cloud Volumes ONTAP. 
---
= Configuraciones compatibles para Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud admite varias configuraciones de Cloud Volumes ONTAP.



== Configuraciones admitidas por licencia

Cloud Volumes ONTAP está disponible en Google Cloud como un sistema de nodo único y como un par de nodos de alta disponibilidad (HA) para tolerancia a fallos y operaciones sin interrupciones.

No se admite la actualización de un sistema de nodo único a un par de HA. Si quieres cambiar entre un sistema de nodo único y un par de HA, necesitas implementar un sistema nuevo y replicar los datos del sistema existente al nuevo sistema.

Cloud Volumes ONTAP puede ejecutarse en una instancia de máquina virtual reservada o bajo demanda desde el proveedor de cloud. No se admiten soluciones que usan otros tipos de instancia de máquinas virtuales.



=== Sistemas de nodo único

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d,d"]
|===
|  | Freemium | Optimizado ^4^ | Licencia basada en la capacidad (Essentials y Professional) 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 500 GIB  a| 
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos.  La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube.  Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles.



| Tipos de máquina compatibles hacia esta 1  a| 
* c3-standard-4, c3-standard-4-lssd ^5^
* c3-standard-8, c3-standard-8-lssd ^5^
* c3-standard-22, c3-standard-22-lssd ^5^
* c3-standard-44, c3-standard-44-lssd ^5^
* c3-standard-88, c3-standard-88-lssd ^5^
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* n2-estándar-4
* n2-estándar-8

 a| 
* c3-standard-4, c3-standard-4-lssd ^5^
* c3-standard-8, c3-standard-8-lssd ^5^
* c3-standard-22, c3-standard-22-lssd ^5^
* c3-standard-44, c3-standard-44-lssd ^5^
* c3-standard-88, c3-standard-88-lssd ^5^
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de disco compatibles hacia esta 2 3+| Discos persistentes equilibrados ^3^, discos persistentes de alto rendimiento (SSD) ^3^ y discos persistentes estándar (HDD). Las máquinas virtuales C3 solo admiten discos Hyperdisk Balanced. 
|===
Notas:

. ^1^ Las máquinas de la serie n1 ya no están disponibles para su selección en la consola de NetApp al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes. Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8. Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina personalizado-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si ya tiene un sistema en funcionamiento en este tipo de máquina, puede seguir utilizándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^2^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando discos solos. Puede alcanzar el límite de capacidad en https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Más información acerca de los límites de discos en Google Cloud"].

. ^3^ El rendimiento de escritura mejorado se activa cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).
. ^4^ A partir del 11 de agosto de 2025, la licencia optimizada de Cloud Volumes ONTAP quedará obsoleta y ya no estará disponible para compra ni renovación en el mercado de Google Cloud para suscripciones de pago por uso (PAYGO).  Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Novedades en Cloud Volumes ONTAP"^] .
. ^5^ Puedes implementar la nueva generación de máquinas virtuales de la familia C3 en Cloud Volumes ONTAP 9.18.1 y versiones posteriores. Las máquinas c3-standard-44 y c3-standard-88 y sus variantes LSSD admiten ancho de banda de nivel 1 en Google Cloud Console de forma predeterminada. Con los tipos de máquinas virtuales C3, no puedes añadir un disco a un agregado existente ni cambiar a otra variante dentro de la familia C3. Consulta link:reference-configs-gcp.html#flash-cache-support["Soporte de Flash Cache"] para más información sobre las variantes LSSD.


--
.Otras licencias
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explora | Norma PAYGO | PAYGO Premium | BYOL basado en nodos 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TB HACIA ARRIBA 2 | 10 TIB | 368 TIB | 368 TIB por licencia 


| Tipos de máquina compatibles con esta versión 3  a| 
* c3-standard-4, c3-standard-4-lssd ^5^
* n2-estándar-4

 a| 
* c3-standard-8, c3-standard-8-lssd ^5^
* n1-standard-8 ^3^
* n2-estándar-8

 a| 
* c3-standard-22, c3-standard-22-lssd ^5^
* c3-standard-44, c3-standard-44-lssd ^5^
* c3-standard-88, c3-standard-88-lssd ^5^
* n1-standard-32 ^3^
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* c3-standard-4, c3-standard-4-lssd ^5^
* c3-standard-8, c3-standard-8-lssd ^5^
* c3-standard-22, c3-standard-22-lssd ^5^
* c3-standard-44, c3-standard-44-lssd ^5^
* c3-standard-88, c3-standard-88-lssd ^5^
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de disco admitidos 4+| Discos persistentes equilibrados ^4^, discos persistentes de alto rendimiento (SSD) ^4^ y discos persistentes estándar (HDD). Las máquinas virtuales C3 solo admiten discos Hyperdisk Balanced. 
|===
Notas:

. ^1^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando discos solos. Puede alcanzar el límite de capacidad en https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Más información acerca de los límites de discos en Google Cloud"].

. ^2^ La organización en niveles de datos en Google Cloud Storage no es compatible con PAYGO Explore.
. ^3^ Las máquinas de la serie n1 ya no están disponibles para su selección en la consola al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes. Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8. Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina personalizado-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si ya tiene un sistema en funcionamiento en este tipo de máquina, puede seguir utilizándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^4^ El rendimiento de escritura mejorado se activa cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).
. ^5^ Puedes implementar la nueva generación de máquinas virtuales de la familia C3 en Cloud Volumes ONTAP 9.18.1 y versiones posteriores. Las máquinas c3-standard-44 y c3-standard-88 y sus variantes LSSD admiten ancho de banda de nivel 1 en Google Cloud Console de forma predeterminada. Con los tipos de máquinas virtuales C3, no puedes añadir un disco a un agregado existente ni cambiar a otra variante dentro de la familia C3. Consulta link:reference-configs-gcp.html#flash-cache-support["Soporte de Flash Cache"] para más información sobre las variantes LSSD.


La consola muestra un tipo de máquina compatible adicional para Estándar y BYOL: n1-highmem-4. Sin embargo, este tipo de máquina no está diseñada para entornos de producción. Lo hemos puesto a disposición únicamente para un entorno de laboratorio específico.

--
====
Para obtener más información sobre tipos de máquinas específicas, consulte la documentación de Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["Tipos de máquinas de uso general de la serie n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipos de máquinas de uso general de la serie N2"^]




=== Pares de alta disponibilidad (HA)

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d,d"]
|===
|  | Freemium | Optimizado ^4^ | Licencia basada en la capacidad (Essentials y Professional) 


| Capacidad máxima del sistema según la licencia (discos + almacenamiento de objetos) | 500 GIB  a| 
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos.  La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube.  Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles.



| Tipos de máquina compatibles hacia esta 1  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* n2-estándar-4
* n2-estándar-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de disco compatibles hacia esta 2 3+| Discos persistentes equilibrados ^3^, discos persistentes Performance (SSD) ^3^ y discos persistentes Standard (HDD). 
|===
Notas:

. ^1^ Las máquinas de la serie n1 ya no están disponibles para su selección en la consola de NetApp al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes. Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8. Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina personalizado-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si ya tiene un sistema en funcionamiento en este tipo de máquina, puede seguir utilizándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^2^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando discos solos. Puede alcanzar el límite de capacidad en https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Más información acerca de los límites de discos en Google Cloud"].

. ^3^ El rendimiento de escritura mejorado se activa cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).
. ^4^ A partir del 11 de agosto de 2025, la licencia optimizada de Cloud Volumes ONTAP quedará obsoleta y ya no estará disponible para compra ni renovación en el mercado de Google Cloud para suscripciones de pago por uso (PAYGO).  Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Novedades en Cloud Volumes ONTAP"^] .


--
.Otras licencias
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explora | Norma PAYGO | PAYGO Premium | BYOL basado en nodos 


| Capacidad máxima del sistema según la licencia (discos + almacenamiento de objetos) | 2 TB HACIA ARRIBA 2 | 10 TIB | 368 TIB | 368 TIB por licencia 


| Tipos de máquina compatibles con esta versión 3  a| 
* n2-estándar-4

 a| 
* n1-standard-8 ^3^
* n2-estándar-8

 a| 
* n1-standard-32 ^3^
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de disco admitidos 4+| Discos persistentes equilibrados ^4^, discos persistentes Performance (SSD) ^4^ y discos persistentes Standard (HDD). 
|===
Notas:

. ^1^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando discos solos. Puede alcanzar el límite de capacidad en https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organización en niveles de los datos inactivos en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Más información acerca de los límites de discos en Google Cloud"].

. ^2^ La organización en niveles de datos en Google Cloud Storage no es compatible con PAYGO Explore.
. ^3^ Las máquinas de la serie n1 ya no están disponibles para su selección en la consola al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes. Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8. Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina personalizado-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si ya tiene un sistema en funcionamiento en este tipo de máquina, puede seguir utilizándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^4^ El rendimiento de escritura mejorado se activa cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).


La consola muestra un tipo de máquina compatible adicional para Estándar y BYOL: n1-highmem-4. Sin embargo, este tipo de máquina no está diseñada para entornos de producción. Lo hemos puesto a disposición únicamente para un entorno de laboratorio específico.

--
====
Para obtener más información sobre tipos de máquinas específicas, consulte la documentación de Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["Tipos de máquinas de uso general de la serie n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipos de máquinas de uso general de la serie N2"^]




== Soporte de Flash Cache

A partir de Cloud Volumes ONTAP 9.13.0, _Flash Cache_, alta velocidad de escritura y una unidad de transmisión máxima (MTU) superior de 8.896 bytes, están disponibles para las siguientes instancias de puesta en marcha de par de alta disponibilidad:

* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64


Puedes habilitar _Flash Cache_ y alta velocidad de escritura al desplegar un tipo de instancia elegible. Para habilitar la unidad de transmisión máxima de 8,896 bytes, debes elegir VPC-1, VPC-2 o VPC-3 para el despliegue. La MTU más alta permite un mayor rendimiento de red. Para más información sobre cómo lanzar uno de estos despliegues, consulta https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html["Lanzar Cloud Volumes ONTAP en Google Cloud"^].


NOTE: _Flash Cache_, el modo de escritura alta y un valor MTU de 8,896 dependen de las funciones y no se pueden deshabilitar individualmente dentro de una instancia configurada.

A partir de Cloud Volumes ONTAP 9.18.1, si seleccionas las variantes de SSD local (LSSD) de las máquinas virtuales C3, Flash Cache se activa de forma predeterminada. Revisa esta tabla para entender la variante de máquina virtual y el número máximo de LSSD que admiten:

[cols="1,1"]
|===
| Tipo de VM | Número de discos LSSD conectados 


| c3-standard-4-lssd | 1 


| c3-standard-8-lssd | 2 


| c3-standard-22-lssd | 4 


| c3-standard-44-lssd | 8 


| c3-standard-88-lssd | 16 
|===


== Capacidad máxima del sistema según el tipo de VM

[cols="3*"]
|===
| Tipo de VM | Máximo de discos de datos compatibles | Capacidad máxima (en TiB) 


| n2 (todas las variantes) | 124 | 257 


| c3-standard-4 | 12 | 256 


| c3-standard-8 | 12 | 256 


| c3-standard-22 | 28 | 256 


| c3-standard-44 | 28 | 512 


| c3-standard-88 | 28 | 512 


| c3-standard-4-lssd | 12 | 256 


| c3-standard-8-lssd | 12 | 256 


| c3-standard-22-lssd | 28 | 256 


| c3-standard-44-lssd | 28 | 512 


| c3-standard-88-lssd | 28 | 512 
|===


== Tamaños de disco admitidos

En Google Cloud, un agregado puede contener hasta 6 discos con el mismo tipo y tamaño. Se admiten los siguientes tamaños de disco:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== Regiones admitidas

Para obtener soporte de región de Google Cloud, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^].
