---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.19.1 incluye una nueva mejora. 
---
= Novedades en Cloud Volumes ONTAP 9.19.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ya puedes desplegar y actualizar a Cloud Volumes ONTAP 9.19.1. Puedes ver la versión base de este lanzamiento y las últimas versiones de parches disponibles para desplegar y actualizar en la NetApp Console.

Para conocer más sobre las funciones de Cloud Volumes ONTAP, las configuraciones compatibles, los límites y más, consulta https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Documentación de Cloud Volumes ONTAP"^].



[[9-19-1-rc-13-july-2026]]
== 9.19.1 RC (13 de julio de 2026)

La versión candidata (RC) de Cloud Volumes ONTAP 9.19.1 ya está disponible para su implementación y actualización únicamente en Google Cloud. Esta versión no está disponible para su implementación y actualización en Amazon Web Services (AWS) ni en Microsoft Azure (Azure).



[[upgrade-notes]]
== Notas de actualización

Lea estas notas para obtener más información acerca de cómo actualizar a esta versión.



[[how-to-upgrade]]
=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde la consola. No debe actualizar Cloud Volumes ONTAP mediante el Administrador del sistema o la CLI. Hacerlo puede afectar la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprende cómo actualizar cuando la consola te lo notifique"^] .



[[supported-upgrade-path]]
=== Ruta de actualización admitida

Puedes actualizar a Cloud Volumes ONTAP 9.19.1 RC desde la 9.18.1 solo en Google Cloud. La consola te pedirá que actualices los sistemas Cloud Volumes ONTAP que cumplan los requisitos a esta versión.


NOTE: En AWS y Azure, no se te pedirá que actualices a la versión 9.19.1 RC porque esta versión no está disponible para implementación ni actualización para estos proveedores de nube.



[[downtime]]
=== Tiempo de inactividad

* La actualización de un sistema de un solo nodo deja el sistema fuera de línea durante hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad es sin interrupciones y las I/O no interrumpen. Durante este proceso de actualización no disruptivo, cada nodo se actualiza en tándem para continuar sirviendo I/O a los clientes.

